### ISSUE TITLE
HealthProfessional and HealthProfessionalRole 

### ISSUE THREAD

**Issue by rlindstrm** [Xt-EHR/xt-ehr-common#15]
Right now HP and HPRole are different models, following FHIR pattern.
However, I don't think we actually have a use case for HP without a role, so maybe we could keep it in one model to make it clearer? Mapping to FHIR would show how it actually maps to two resources.

**Comment by costateixeira** [comment]
Agree

**Comment by rlindstrm** [comment]
Feedback from Task 6.2:
- consider having personalIdentifier and professionalIdentifier for practitioner (subelements of Identifier).
- add contactInformation BackboneElement and move address and telecom under it (like with Patient)
- remove "OfTheHp" from element names (it's in the name of the model).
- address is on HealthProfessional and HealthProfessionalRole.organization both. Needs textual clarification when to use what.
- qualification? There could be something on HealthProfessional level in that regard.
- HealthProfessionalRole has role and specialty. Needs clarification what goes where (also consider qualification in HealthProfessional.

Did not reach full agreement whether it's safe to merge the two models within EHDS data exchange context ([IHE model ](https://build.fhir.org/ig/IHE/pharm-mpd/StructureDefinition-PractitionerBasic.html) does the merging but does not fully match the data requirements we have here). When merged, we can always refer to one model and the organisation info may or may not be filled in.

In addition, we verified that EHDS uses the term HealthProfessional and it's a very good name for the model (we were not sure for a moment).

**Comment by rlindstrm** [comment]
Just a note (for myself mainly): for now, eP/eD models use only HealthProfessional reference just to keep the model prettier. But if we decide to keep both, we will add the other reference back.

**Comment by danka74** [comment]
DK agrees to only use HP+HPR (a HP with multiple roles will only be applying one of them at a given point in time)

**Comment by danka74** [comment]
@kruzikh will consider impact on WP7 logical models

**Comment by rlindstrm** [comment]
Will be merged to HealthProfessional. @rlindstrm

**Comment by rlindstrm** [comment]
HP and HP Role are now merged. 
HealthProfessionalRole references have not been removed yet. 
Role, specialty and qualification needs further clarification.

**Comment by danka74** [comment]
2024-10-30:
Main use case is one professional performing in one role in a given situation.
There might be additional use cases (e.g. a HP registry) for which there is currently no requirement.
