### ISSUE TITLE
Medication adminstration batch number

### ISSUE THREAD

**Issue by danka74** [Xt-EHR/xt-ehr-common#16]
The "Vaccination" section of the EUPS and MyHealth@EU (optinal) has batch number for the vaccine medication products. Do we want/need/etc. to reuse MedicinalProduct or MedicationAdministration for vaccination?

**Comment by danka74** [comment]
T6.2 WG meeting 2024-09-20:
Batch number required for biological MPs (administration and dispense?)

**Comment by costateixeira** [comment]
Usually yes, either batch or serial, or some other form of traceability to
source.
Ate those products in scope?
In FHIR they may be using other resources, not med ones

**Comment by rlindstrm** [comment]
Added batch lot number and expiry date - modelled the same way as they appear in FHIR resource.
