### ISSUE TITLE
Prescription intent (prophylaxis, treatment, anesthesia)

### ISSUE THREAD

**Issue by rlindstrm** [Xt-EHR/xt-ehr-common#18]
The data element "intended use" is in Patient Summary medication section. Should we add it in the prescription model, too?

It exists in IHE Medication Overview, but also in Patient Summary - so if that information has to be there, it must be sourced from somewhere. In some cases semantically included in reason/indication. Definitely an optional element.

Will be discussed with the big T6.2 group if there is a need for such data element in prescription context.

**Comment by costateixeira** [comment]
In the upcoming Belgian ePrescription specification, "Prophylaxis / Therapy" has been presented as a requirement. The element was called "Exposure" and has not been added to the model yet, but we are awaiting confirmation about some aspects including this one.

**Comment by danka74** [comment]
| |Intended use|
|----|----|
|Conformant (%) |0%|
| 1 - not available |81%|
| 2 - not structured |6%|
| 3 - structured not coded |0%|
| 4 - structured, but not compatible |0%|
| 5 - national code system, no mapping to MVC |0%|
| N/A |0%|
| NC |13%|

**Comment by rlindstrm** [comment]
French inpatient MedicationRequest seems to have treatmentIntent as an extension:
https://interop-sante.github.io/hl7.fhir.fr.medication/main/ig/StructureDefinition-FrTeatmentIntent.html 

ValueSet binding to <363675004 |Intents (nature of procedure values) (qualifier value)|

**Comment by rlindstrm** [comment]
20.09. T6.2 meeting inclines to add it as optional element, but not entirely sure if this should be for prescription or prescription line.

**Comment by danka74** [comment]
Perhaps to be corroborated by a MS with multiline prescriptions, but reasonable to allow different intended use per prescription item rather than disallowing it. Users can always put the same intended use on all items and enforce rules checking data in such ways during generation/collection.
