### ISSUE TITLE
Missing elements in medication domain models

### ISSUE THREAD

**Issue by danka74** [Xt-EHR/xt-ehr-common#23]
1. Package type - Type of the container. Examples: bottle, blister, box
1. Prescription repeats - related to [quantityPrescribed](https://build.fhir.org/ig/Xt-EHR/xt-ehr-common/StructureDefinition-EHDSMedicationPrescription-definitions.html#EHDSMedicationPrescription.prescriptionItem.quantityPrescribed) but not quite the same. Guideline has description "In some countries, when medicinal products are dispensed for the first time, the patient may only receive medication for a short period of time. When a patient starts taking medication for a chronic illness, the prescriber can issue a prescription for a longer period that is now separated by repeats. In addition, the maximum quantity (A.1.4.3) of the prescribed product that may be dispensed in one dispensation may be stated here. Decision on dispensability is made in the country of prescription."
~~Starting date of therapy - The time and date on which it is agreed that therapy will start.~~

**Comment by rlindstrm** [comment]
1) I propose to leave it out. When relevant, it's usually contained in the dose form anyway. Typically not filled in, esp on prescriptions.
2) Here it was unclear what exactly to record in the model - everything that exists in FHIR?
3) effectiveDosePeriod will be added, this will cover the element. https://github.com/IHE/pharm-mpd/issues/43

**Comment by danka74** [comment]
T62 WG call 2024-09-20:
1. Useful to identify the medicinal product in cross-border situations, it is in MyHealth@EU req. catalogue.
2. FHIR (r4+) has [dispenseRequest.numberOfRepeatsAllowed](https://hl7.org/fhir/R4/medicationrequest-definitions.html#MedicationRequest.dispenseRequest.numberOfRepeatsAllowed)

**Comment by danka74** [comment]
T6.2 call 2024-09-27:
* add 1 and 2 to logical models,
