### ISSUE TITLE
Authoring, authentication and validation date and time

### ISSUE THREAD

**Issue by johannes-holm** [Xt-EHR/xt-ehr-common#26]
Right now in Imaging Report Header (I belive in other headers as well) the author, attester and the legal authenticator reference all reference to a EHDSHealthProfessionalRole. However there needs to be a reference to date and time of authoring, authentication and validation as well, which the EHDSHealthProfessionalRole does not have (nor should it I believe). My suggestion is to make a authoring, validation and authentication BackboneElements which have a reference to the person and a datetime attribute of the process

**Comment by kruzikh** [comment]
Changed description and name of the "authorisation" section according to the recommendation of the group.
