### ISSUE TITLE
Stop using BackboneElement

### ISSUE THREAD

**Issue by danka74** [Xt-EHR/xt-ehr-common#40]
2024-10-30:
Decided to try ut using "Class" instead of BackboneElement as container type in logical models

**Comment by costateixeira** [comment]
if the issue is just one of display, can we check if the tooling could be updated instead?

**Comment by danka74** [comment]
Hmm, I think this is expected result from using BackboneElement. I tried using Base instead and that works without the extra elements.

**Comment by danka74** [comment]
I did a branch with Base instead of BackboneElement: https://build.fhir.org/ig/Xt-EHR/xt-ehr-common/branches/base/artifacts.html

**Comment by rlindstrm** [comment]
06.11.2024
Base seems to be more FHIR core, but maybe not the best option here.
Class is self-defined and might be a better fit. 
Not entirely sure if there's a technical impact specific to either of those options. We'll try Base-approach first.
